/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_handezhao_sudoku_UseNative */

#ifndef _Included_com_github_handezhao_sudoku_UseNative
#define _Included_com_github_handezhao_sudoku_UseNative
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_github_handezhao_sudoku_UseNative
 * Method:    createNewSoduku
 * Signature: (II)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_github_handezhao_sudoku_UseNative_createNewSoduku
        (JNIEnv *, jobject);

/*
 * Class:     com_github_handezhao_sudoku_UseNative
 * Method:    createNewTwoDimensionalArray
 * Signature: (II)[[I
 */
JNIEXPORT jobjectArray JNICALL
Java_com_github_handezhao_sudoku_UseNative_createNewTwoDimensionalArray
        (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
